### ISSUE TITLE
Create a CPAN release?

### ISSUE THREAD

**Issue by hakonhagland** [jandrew/p5-spreadsheet-reader-format#5]
If I go to [Spreadsheet::Reader::ExcelXML](https://metacpan.org/pod/Spreadsheet::Reader::ExcelXML) on metacpan.org and click on the link to [Spreadsheet::Reader::Format](https://metacpan.org/pod/Spreadsheet::Reader::Format) in the description I am redirected to "Error 404 Not Found" page on metacpan.org. Still I can find the distribution under the [author releases page]( https://metacpan.org/author/JANDREW/releases) and if I click on it I end up on [this page](https://metacpan.org/pod/release/JANDREW/Spreadsheet-Reader-Format-v0.6.2/README.pod) on the BackPAN.

Any reason why the module has not been released to CPAN yet (but instead is on the BackPAN)?

**Comment by jandrew** [comment]
Håkon,

I was in the process of splitting the Formatter functionality out and
making it work for all Spreadsheet packages with the intent of aligning
test suites when I changed jobs.  I think the release that was posted at
that time was broken so I deleted it with the intent of re-posting a fixed
one and never did.  This was all complicated by the fact that
Spreadsheet::Reader::ExcelXML is a somewhat controversial package since it
duplicated functionality of several other spreadsheet readers, used a
hand-rolled xml parser, and adds to the fairly crowded namespace.

The short version is you should feel free to post the package to PAUSE
yourself and you will automatically get PAUSE ownership.  I just checked my
PAUSE account and I am not the PAUSE owner for that namespace.  By the way
if you want I can give you co-maint or even owner for the
Spreadsheet-Reader-ExcelXML namespace.

The long version includes the fact that I was distracted by hunting why
very few Unixy systems were not testing this package.  (Yak shaving) It's
because newer excel files are all basically win-zipped globs of files and
you needed a 7zip installation for linux installed and added to PATH as a
minimum for this package to install.  I was trying to get Archive::Zip to
import and install 7zip as a dependency when it didn't exist and
that's where I stopped.  I also describe a few architectural choices in
this link to explain my journey in this link.
https://metacpan.org/pod/distribution/Spreadsheet-Reader-ExcelXML/README.pod#Architecture-Choices

Best Regards,

Jed

**Comment by hakonhagland** [comment]
> I just checked my PAUSE account and I am not the PAUSE owner for that namespace

I am not so familiar with PAUSE. What namespace is that and do we need permission to upload the module?

**Comment by jandrew** [comment]
Håkon,

To place something for visibility in Meta::CPAN you need to have a PAUSE
account.  Go here to login (get an account) and be blessed by the Perl Gods!

https://pause.perl.org/pause/query

Best Regards,

Jed

**Comment by hakonhagland** [comment]
> be blessed by the Perl Gods!

:smile:  Thanks, actually I already have an [account](https://metacpan.org/author/HAKONH). I [checked the permissions](https://metacpan.org/pod/PAUSE::Permissions) of `Spreadsheet::Reader::Format`, and it gave me:

```
Name space: Spreadsheet::Reader::Format
Owner     : JANDREW
Comaints  : None
```
I can try upload a release if you assign me comaintainer status?

**Comment by jandrew** [comment]
OK,

So it looks like there is a gap here.  I don't have a co-maint choice
in PAUSE, probably because there isn't an active distribution right now.  I
did give you co-maint for SpreadSheet::Reader::ExcelXML.

If you send me the tar.gz file you were planning on uploading I can load it
once which should turn the sharing menu back on.  If you are willing.

Best Regards,

Jed

**Comment by hakonhagland** [comment]
I have sent you the tarball per email.

**Comment by jandrew** [comment]
Håkon,

That did the trick.

HAKONH is now Comaint on that name space.

Best Regards,

Jed

**Comment by hakonhagland** [comment]
Great!
